backend:
  name: github
  repo: Malhelel/Malhelel.github.io
  branch: main
  
media_folder: "images/uploads"

collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "_data/homepage.yml"
        label: "Homepage"
        name: "home"
        fields:
          - { label: "Hero Title", name: "hero_title", widget: "string" }
          - { label: "Hero Subtitle", name: "hero_subtitle", widget: "text" }
          - { label: "Sidebar Slogan", name: "sidebar_slogan", widget: "string" }
  - name: "posts"
    label: "Articles"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }
